from transformers import PegasusForConditionalGeneration, PegasusTokenizer

model_name = "google/pegasus-xsum"
tokenizer = PegasusTokenizer.from_pretrained(model_name)
model = PegasusForConditionalGeneration.from_pretrained(model_name)

article = """
Providing timely feedback is crucial in promoting academic achievement and student success. However, for multifarious reasons (e.g., limited teaching resources), feedback often arrives too late for learners to act on the feedback and improve learning. Thus, automated feedback systems have emerged to tackle educational tasks in various domains, including novice programming, short-essay writing, and open-ended questions. However, to the best of our knowledge, no previous study has investigated automated feedback generation on students’ project reports. In this paper, we present a novel data-driven system, named Insta-Reviewer, for automatically generating instant feedback on students’ project reports, using state-of-the-art natural language processing (NLP) models. We also propose a framework for manually evaluating system-generated feedback. Experimental results show that feedback generated by Insta-Reviewer on real students’ project reports can achieve near-human performance. Our work demonstrates the feasibility of automatic feedback generation for students’ project reports while highlighting several prominent challenges for future research.
"""
# print(len(article.split(' ')))

min_length = round(len(article.split(' '))*30/100)

# # create tokens - number representation of our text
# tokens = tokenizer(article, truncation = True, padding = "longest", return_tensors = "pt")

# # summarize
# summary = model.generate(**tokens)

# # decode summary
# summary = tokenizer.decode(summary[0])
# print(summary)

input_tokens = tokenizer(
    article,
    return_tensors='pt',
    max_length=1024,
    truncation=True)

encoded_ids = model.generate(**input_tokens, min_length= min_length)
summary = tokenizer.decode(encoded_ids[0].squeeze(), skip_special_tokens=True)
print(summary)

